@startuml
class "CompareModels" as C1 {
}
class "LogisticRegression" as C2 {
}
class "Middleware_API" as C3 <<QuantumDriver>> {
}
note right of C3
  quantum_hw_constraint: NISQ
  quantum_hw_constraint: FourQubits
end note
class "ProvideQuantumPrediction" as C4 {
}
class "UnderstandModelPerformance" as C5 {
}
class "VQC" as C6 <<Quantum>> {
}
note right of C6
  quantum_hw_constraint: NISQ
  quantum_hw_constraint: FourQubits
end note
C5 ..> C1 : requires
C1 ..> C4 : requires
C4 ..> C6 : requires
C6 ..> C3 : requires
@enduml
